version: "3.9"
services:
  mysql:
    image: mysql
    platform: linux/x86_64
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=order_db
    command: --default-authentication-plugin=mysql_native_password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  order:
    image: dove-cqrs/order
    build: services/order-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - kafka

  customer:
    image: dove-cqrs/customer
    build: services/customer-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - kafka

  restaurant:
    image: dove-cqrs/restaurant
    build: services/restaurant-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - kafka

  payment:
    image: dove-cqrs/payment
    build: services/payment-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - kafka

  kitchen:
    image: dove-cqrs/kitchen
    build: services/kitchen-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - kafka

  delivery:
    image: dove-cqrs/delivery
    build: services/delivery-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - kafka

  history:
    image: dove-cqrs/history
    hostname: history
    build: services/order-history-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - elasticsearch
      - kafka

  debezium-server:
    image: dove-cqrs/debezium-server
    build: services/debezium-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - $PWD/data/:/data/
    depends_on:
      - mysql
      - kafka
      - order