server:
  port: 8087
  shutdown: graceful

spring:
  application:
    name: order-history-service
  data:
    elasticsearch:
      host: localhost
      port: 9200

      index:
        name: board
        shards: 1
        replicas: 0
  cloud:
    function:
      definition: orderMessageConsumer
    stream:
      default-binder: kafka
      default:
        contentType: application/json
      bindings:
        orderMessageConsumer-in-0:
          destination: order-reply
          group: historyGroup
        orderMessageConsumer-in-0.consumer:
          - maxAttempts=3
          - backOffInitialInterval=500
          - backOffMaxInterval=1000
          - backOffMultiplier=2.0
      kafka:
        bindings:
          orderMessageConsumer-in-0.consumer:
            - enableDlq=true
        binder:
          brokers: localhost
        defaultBrokerPort: 9092
  lifecycle:
    timeout-per-shutdown-phase: 10s

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    elasticsearch:
      host: elasticsearch
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka