server:
  port: 8086
  shutdown: graceful

spring:
  application:
    name: delivery-service
  r2dbc:
    username: root
    password: root
    url: localhost:3306/order_db?characterEncoding=UTF-8&useSSL=false
  lifecycle:
    timeout-per-shutdown-phase: 10s

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: mysql:3306/order_db?characterEncoding=UTF-8&useSSL=false