server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: order-service
  r2dbc:
    username: root
    password: root
    url: localhost:3306/order_db?characterEncoding=UTF-8&useSSL=false
  cloud:
    function:
      definition: orderReplyMessageConsumer
    stream:
      default-binder: kafka
      default:
        contentType: application/json
      bindings:
        orderReplyMessageConsumer-in-0:
          destination: order-reply
          group: orderGroup
        orderReplyMessageConsumer-in-0.consumer:
          - maxAttempts=3
          - backOffInitialInterval=500
          - backOffMaxInterval=1000
          - backOffMultiplier=2.0
      kafka:
        bindings:
          orderReplyMessageConsumer-in-0.consumer:
            - enableDlq=true
        binder:
          brokers: localhost
        defaultBrokerPort: 9092
  lifecycle:
    timeout-per-shutdown-phase: 10s

logging:
  level:
    root: info

---
spring:
  config:
    activate:
      on-profile: docker
  r2dbc:
    url: mysql:3306/order_db?characterEncoding=UTF-8&useSSL=false
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka